### ISSUE TITLE
Look into transfers pertaining to 10 player limit

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#249]
I know we've brought this up before but can we have another consider about allowing transfers if they have put somebody to transfer out and have a notification or something saying if your transfer out is denied, Your transfer in wont be allowed or something similar.

**Comment by BenjaminSchaaf** [comment]
Consider the case that there is a request for a transfer out and in. What happens when the transfer in is accepted? What happens when the transfer out is denied?

Now consider what happens when there are multiple transfers in and out. And even worse what happens when a team has more members than the limit?

**Comment by obla** [comment]
If a team has 10 players and is transferring players out, have a pop up notification saying the following.

'If you wish to transfer a player(s) in, please contact your bracket's administrator to coordinate a player swap.'

Thoughts?

**Comment by BenjaminSchaaf** [comment]
Thats more stepping around the issue than solving it

**Comment by obla** [comment]
What do you suggest then? Solving it seems to have a lot of issues on your end.

**Comment by yauchh** [comment]
Is it possible to allow transfers in to be submitted by team captains but make it physically impossible for us to accept if they have 10 players? With a 'Roster is at its 10 player limit' popup like obla suggested but for us instead of people requesting the transfer. If they haven't got enough room then we message the captain and make sure to shout about the 10 player limit rule etc. Then all that means is we have to make sure to do transfers out before we do transfers in at the end of each week.

**Comment by BenjaminSchaaf** [comment]
@yauchh Yea, thats possible. But I'm worried with that about abuse, consider a team that has a ridiculous amount of players in it, now the captain can spam requests.

**Comment by yauchh** [comment]
Could consider a Weekly transfer limit in that case? Idk what other connotations that might have though

**Comment by obla** [comment]
No to additional rules. Should try to solve this issue directly.

**Comment by obla** [comment]
Ideally we want it with as limited interactions between admins and captains as possible.

**Comment by yauchh** [comment]
Is it possible to register transfers out as a space on the roster as far as the transfer is concerned? So you can apply for transfers in if you have applied for the required amount of transfers out. Idk if thats viable tho

**Comment by BenjaminSchaaf** [comment]
@yauch that would work, but I can't think of a way in which it wouldn't hurt the admin UX when accepting transfers. Transfers in couldn't be accepted before transfers out have been and the ordering means they could be all over the place. We could (maybe) also change the ordering of transfer requests to group rosters together, but that doesn't really work when transfers are between 2 rosters.

**Comment by BenjaminSchaaf** [comment]
So I think it boils down to which is preferable: More complicated admin UX when managing transfers and simpler user UX, or admins manually handle overflow situations.

**Comment by obla** [comment]
Something that is simpler for the end user (not admins, but players) is better.

**Comment by BenjaminSchaaf** [comment]
Alright
