### ISSUE TITLE
Match Description

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#95]
i.e.:
To be played between:
Sunday 1st August, 2016 - Thursday 5th August, 2016

**Comment by BenjaminSchaaf** [comment]
Do you think a more general 'match notice' would work better? It'd be more dynamic than having a bunch of optional fixed fields that the system mostly ignores.

**Comment by obla** [comment]
Sure, that works too.

**Comment by BenjaminSchaaf** [comment]
With schedulers built in now, is this still a desired feature?

**Comment by AndKenneth** [comment]
Can this feature not just be covered by standard match comms?

**Comment by BenjaminSchaaf** [comment]
Sure, it'd be a matter of doing the controller/service logic

**Comment by AndKenneth** [comment]
I was thinking from an end user experience point of view rather than using the same backend system. In my mind match comments == match communications. I was agreeing that this feature could be rejected.

If you have a different idea @obla that necessitates the seperation of match notices/comments and match communications? If you wanted to seperate out and highlight system notices or admin messages, potentially this could be done in the same feed as match comms but highlighted using some front end styling.

**Comment by obla** [comment]
Was hoping this feature could still be implemented as it's just a static line. Match negotiation is still a thing as default date is not forced until Sunday evening. My idea was to not have this feature as a match comment/communication, but below the rosters (or wherever you feel suits). 

Administrator comments styling would be nice too i.e. different shade background + coloured border.

**Comment by AndKenneth** [comment]
Almost like a match "description"?

**Comment by obla** [comment]
Yes.

**Comment by AndKenneth** [comment]
opened issue https://github.com/ozfortress/citadel/issues/115 for admin match comm styling.
